version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/home/app/web/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  redis:
    image: "redis"

  celery:
    build: .
    command: celery -A mhq_web worker -l info
    volumes:
      - .:/home/app/web/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A mhq_web beat -l info
    volumes:
      - .:/home/app/web/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mhq
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mhqDB

volumes:
  postgres_data: