# Generated by Django 3.2 on 2021-05-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20210425_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
