# Generated by Django 3.1.7 on 2021-05-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0003_auto_20210425_2233'),
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.request')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.scenario')),
            ],
            options={
                'db_table': 'module',
            },
        ),
    ]
