# Generated by Django 3.2 on 2021-05-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='x_position',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='y_position',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
