# Generated by Django 3.2.3 on 2021-06-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_auto_20210518_2234'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table=None,
        ),
    ]
