# Generated by Django 3.2.3 on 2021-06-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_requesthistory'),
        ('module', '0002_auto_20210518_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.request'),
        ),
    ]
