# Generated by Django 3.2.3 on 2021-06-10 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_auto_20210610_0423'),
        ('request', '0004_requesthistory'),
        ('module', '0002_auto_20210518_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.request'),
        ),
        migrations.AlterField(
            model_name='module',
            name='scenario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scenario.scenario'),
        ),
        migrations.AlterField(
            model_name='module',
            name='x_position',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='module',
            name='y_position',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
