# Generated by Django 3.2.3 on 2021-06-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_alter_module_table'),
        ('module', '0003_auto_20210610_0524'),
    ]

    operations = [
    ]
