# Generated by Django 3.2.3 on 2021-06-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_merge_0003_alter_module_table_0003_auto_20210610_0524'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table='module',
        ),
    ]
