# Generated by Django 3.1.7 on 2021-05-04 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist', to='module.module')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='module.module')),
            ],
            options={
                'db_table': 'edges',
                'unique_together': {('source', 'dist')},
            },
        ),
    ]
