# Generated by Django 3.2.3 on 2021-05-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('edge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statement_of', to='edge.edge')),
            ],
            options={
                'db_table': 'conditions',
            },
        ),
    ]
