# Generated by Django 3.2.3 on 2021-05-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0002_statement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statement',
            table='statements',
        ),
    ]
