# Generated by Django 3.2.3 on 2021-06-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0003_alter_statement_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_of', to='edge.edge'),
        ),
    ]
