# Generated by Django 3.1.7 on 2021-04-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20210412_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='http_method',
            field=models.CharField(blank=True, default='get', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='KeyValueContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='header', max_length=255)),
                ('enable', models.BooleanField(default=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.request')),
            ],
        ),
    ]
