# Generated by Django 3.2.3 on 2021-06-13 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20210613_0536'),
        ('request', '0004_requesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.module'),
        ),
    ]
