# Generated by Django 3.2.3 on 2021-06-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20210612_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='status',
            field=models.CharField(blank=True, default='progress', max_length=200),
        ),
    ]
