# Generated by Django 3.2.3 on 2021-06-13 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_auto_20210613_0631'),
        ('request', '0005_requesthistory_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='scenario_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenario.scenariohistory'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='status',
            field=models.CharField(blank=True, default='progress', max_length=200),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='type',
            field=models.CharField(blank=True, default='single', max_length=200),
        ),
        migrations.AlterModelTable(
            name='requesthistory',
            table='request_histories',
        ),
    ]
