# Generated by Django 3.2.3 on 2021-06-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0010_alter_scenariohistory_start_request_time'),
        ('module', '0005_alter_module_table'),
        ('request', '0006_alter_requesthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.module'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='scenario_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenario.scenariohistory'),
        ),
    ]
