# Generated by Django 3.2.3 on 2021-05-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('module', '0002_auto_20210518_2234'),
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='starter_module',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='starter_module', to='module.module'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='intervals', max_length=255)),
                ('enable', models.BooleanField(default=False)),
                ('minutes', models.IntegerField(default=15, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('time', models.TimeField(null=True)),
                ('days', models.CharField(max_length=255, null=True)),
                ('months', models.CharField(max_length=255, null=True)),
                ('start_date_time', models.DateTimeField(null=True)),
                ('expired_date_time', models.DateTimeField(null=True)),
                ('periodic_task', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario.schedule'),
        ),
    ]
