# Generated by Django 3.2.3 on 2021-05-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('scenario', '0002_auto_20210529_0201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='ScenarioSchedule',
        ),
        migrations.AlterModelTable(
            name='scenarioschedule',
            table='scenario_schedules',
        ),
    ]
