# Generated by Django 3.2.3 on 2021-06-06 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collection_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenario', '0003_auto_20210529_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.CharField(max_length=200)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection')),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenario.scenario')),
                ('schedule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario.scenarioschedule')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenario_history',
            },
        ),
    ]
