# Generated by Django 3.2.3 on 2021-06-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_auto_20210518_2234'),
        ('scenario', '0003_auto_20210529_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario.scenarioschedule'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='starter_module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='starter_module', to='module.module'),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='expired_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='minutes',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='months',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
