# Generated by Django 3.2.3 on 2021-06-13 01:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collection_name'),
        ('module', '0003_auto_20210613_0536'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenario', '0003_auto_20210529_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario.scenarioschedule'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='starter_module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='starter_module', to='module.module'),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='expired_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='minutes',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='months',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioschedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScenarioHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_request_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_execution_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('schedule', models.CharField(default='once', max_length=200, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection')),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenario.scenario')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenario_history',
            },
        ),
    ]
