# Generated by Django 3.2.3 on 2021-06-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_auto_20210608_2142'),
        ('scenario', '0004_scenariohistory'),
    ]

    operations = [
    ]
