# Generated by Django 3.2.3 on 2021-06-13 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collection_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenario', '0004_auto_20210608_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ScenarioHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_request_time', models.DateTimeField(auto_now_add=True)),
                ('end_execution_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('schedule', models.CharField(default='once', max_length=200, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection')),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenario.scenario')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenario_history',
            },
        ),
    ]
