# Generated by Django 3.2.3 on 2021-06-09 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collection_name'),
        ('scenario', '0004_auto_20210608_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
