# Generated by Django 3.2.3 on 2021-06-12 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_merge_0004_auto_20210608_2142_0004_scenariohistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenariohistory',
            old_name='execution_time',
            new_name='execution_request_time',
        ),
        migrations.RemoveField(
            model_name='scenariohistory',
            name='order',
        ),
        migrations.AddField(
            model_name='scenariohistory',
            name='end_execution_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scenariohistory',
            name='schedule',
            field=models.CharField(default='once', max_length=200, null=True),
        ),
    ]
