# Generated by Django 3.2.3 on 2021-06-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0006_auto_20210612_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenariohistory',
            old_name='execution_request_time',
            new_name='start_request_time',
        ),
        migrations.AlterField(
            model_name='scenariohistory',
            name='end_execution_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
