# Generated by Django 3.2.3 on 2021-06-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0006_auto_20210612_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariohistory',
            name='end_execution_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
