# Generated by Django 3.2.3 on 2021-06-12 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0007_alter_scenariohistory_end_execution_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariohistory',
            name='execution_request_time',
        ),
        migrations.AddField(
            model_name='scenariohistory',
            name='start_request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 1, 51, 29, 254072)),
        ),
        migrations.AlterField(
            model_name='scenariohistory',
            name='end_execution_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
