# Generated by Django 3.2.3 on 2021-06-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_auto_20210610_0423'),
        ('scenario', '0008_auto_20210613_0151'),
    ]

    operations = [
    ]
