# Generated by Django 3.2.3 on 2021-06-12 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0008_auto_20210613_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariohistory',
            name='start_request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 3, 32, 44, 596901)),
        ),
    ]
