# Generated by Django 3.2.3 on 2021-06-13 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0009_merge_0005_auto_20210610_0423_0008_auto_20210613_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariohistory',
            name='start_request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 5, 23, 33, 954698)),
        ),
    ]
