# Generated by Django 3.2.3 on 2021-06-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0004_alter_statement_edge'),
        ('condition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='first_token',
            field=models.CharField(blank=True, default='str', max_length=255),
        ),
        migrations.AddField(
            model_name='condition',
            name='second_token',
            field=models.CharField(blank=True, default='str', max_length=255),
        ),
        migrations.AlterField(
            model_name='condition',
            name='first',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='operator',
            field=models.CharField(blank=True, default='equal', max_length=255),
        ),
        migrations.AlterField(
            model_name='condition',
            name='second',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='statement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='edge.statement'),
        ),
    ]
