name: Docker CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Pull front project
      run: |
        cd nginx
        git clone https://github.com/mhq-dev/mhq-front.git
        cd mhq-front
        git checkout develop
        cd ../..
        
    - name: Make env files
      run: |
        echo ${{ secrets.ENV_PROD }} > ./.env.prod
        echo ${{ secrets.ENV_PROD_DB }} > ./.env.prod.db
    
    - name: Build the docker-compose
      run: docker-compose -f docker-compose.prod.yml up -d --build
    
    - name: Check running containers
      run: docker ps
    
    - name: Run tests
      run: docker-compose -f docker-compose.prod.yml exec -T web python manage.py test
